---
title: Mark On Product
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    description: 
    postimage: 
    socialimage: 
    readtime: 
- scope:
    path: ''
    type: pages
  values:
    description: 
markdown: kramdown
rouge: true
permalink: "/:title"
tagline: Product Management In The Real World
description: This is the personal blog of Mark Mitchell. The focus most of the time
  will be my views and experiences leading a Product Management team. Some of the
  time, it can get a little random.
url: https://markonproduct.com
author:
  name: Mark Mitchell
  url: https://twitter.com/MarkMitchell
  bio: Hi! I’m Mark Mitchell. I’m VP of Product at a large financial services company.
    I lead an awesome team of 13 Product Managers. Most of my days are spent helping
    them solve the challenges they come across while delivering some truly great products.
    Like many Product Managers, I traveled an unusual path to get here. <a href="/about-mark-mitchell">Here’s
    the full scoop</a>.
  image: https://res.cloudinary.com/dbrkuvff5/image/upload/v1533636293/post-images/mark-mitchell-bio-photo.gif
paginate: 5
version: 1.2.3
github:
  repo: https://github.com/markthelefty/markthelefty.github.io
plugins:
- jekyll-seo-tag
