---
title: Mark On Product
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    test-1: hello
    test-2: world
markdown: kramdown
rouge: true
permalink: "/:title"
tagline: Product Management In The Real World
description: This is the personal blog of Mark Mitchell. The focus most of the time
  will be my views and experiences leading a Product Management team. Some of the
  time, it can get a little random.
url: https://markonproduct.com
author:
  name: Mark Mitchell
  url: https://twitter.com/MarkMitchell
paginate: 5
version: 1.0.0
github:
  repo: https://github.com/markthelefty/markthelefty.github.io
social card image:
  social-image: "/path/to/image.jpg"
meta description:
  meta: 
