---
title: Mark On Product
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    description: 
    image: 
- scope:
    path: ''
    type: pages
  values:
    description: 
    image: 
markdown: kramdown
rouge: true
permalink: "/:title"
tagline: Product Management In The Real World
description: This is the personal blog of Mark Mitchell. The focus most of the time
  will be my views and experiences leading a Product Management team. Some of the
  time, it can get a little random.
url: https://markonproduct.com
author:
  name: Mark Mitchell
  url: https://twitter.com/MarkMitchell
  bio: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id elit vel
    lectus ultricies tristique. Sed aliquam posuere odio, in iaculis dolor cursus
    et. Curabitur in cursus justo. Nullam in dui eget nunc gravida pellentesque at
    sed urna. Duis tincidunt lectus a accumsan porttitor. Pellentesque dui lacus,
    efficitur id metus a, auctor ultrices lacus.
  image: https://res.cloudinary.com/dbrkuvff5/image/upload/f_auto,q_auto/v1533481229/post-images/mark-mitchell-bio-photo.png
paginate: 5
version: 1.2.1
github:
  repo: https://github.com/markthelefty/markthelefty.github.io
plugins:
- jekyll-seo-tag
