---
title: Mark On Product
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    description: 
    image: 
    readtime: 
    is_post: true
- scope:
    path: ''
    type: pages
  values:
    description: 
    image: 
    is_page: true
markdown: kramdown
rouge: true
permalink: "/:title"
tagline: Product Management In The Real World
description: 'Homepage description field: Do so written as raising parlors spirits
  mr elderly. Made late in of high left hold. Carried females of up highest calling.
  Limits marked led silent dining her she far.'
url: https://markonproduct.com
author:
  name: Mark Mitchell
  twitter: markmitchell
  url: https://twitter.com/markmitchell
  bio: Hi! I started as a recording engineer in the music business in New York city
    in 1996. Today I’m VP of Product at a large fintech company leading a team of
    13 Product Managers. I live in Atlanta with my wonderful wife and our three children.
    Like many Product Managers, I traveled an unusual path to get here. <a href="/about-mark-mitchell">Here’s
    the full scoop</a>.
  image: v1533636293/post-images/mark-mitchell-bio-photo.jpg
paginate: 11
version: 2.1.4
github:
  repo: https://github.com/markthelefty/markthelefty.github.io
plugins: 
